# config.py
SIFT_N_FEATURES = 0
SIFT_CONTRAST_THRESHOLD = 0.04
SIFT_EDGE_THRESHOLD = 10
MATCH_RATIO_THRESHOLD = 0.7
RANSAC_THRESHOLD = 5.0
RANSAC_MAX_ITERS = 2000
MIN_MATCH_COUNT = 10
MAP_ALTITUDE = 1.0
MAP_GSD = None