# config.py
SIFT_N_FEATURES = 0
SIFT_CONTRAST_THRESHOLD = 0.01
SIFT_EDGE_THRESHOLD = 12
MATCH_RATIO_THRESHOLD = 0.7
RANSAC_THRESHOLD = 6.0
RANSAC_MAX_ITERS = 2000
MIN_MATCH_COUNT = 10
MAP_ALTITUDE = 1.0
MAP_GSD = None